cluster.name: es-cluster
node.name: es03
node.master: true
path.data: /usr/share/elasticsearch/data/
path.logs: /usr/share/elasticsearch/logs/
#bootstrap.memory_lock: true
network.host: 0.0.0.0
http.port: 9200
transport.port: 9300
discovery.seed_hosts: ["es01","es02"]
cluster.initial_master_nodes: ["es01","es02","es03"]
